server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wanted_feed_service?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      port: 6379
      host: 127.0.0.1

  mail:
    host: smtp.gmail.com
    port: 587
    username: wanted.intership.service@gmail.com
    password: 123qwe!@#QWE
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부(기본값 false)
          timeout: 5000 # Socket Read Timeout 시간 (ms) (기본값 무한대)
          starttls:
            enable: true # StartTLS 활성화 여부(기본값: false)

springdoc:
  version: v1.0.0
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
